version: "3.3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  web:
    image: fjfdepedro/rails_postgres:6
    volumes:
      - .:/rails_postgres
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      PGHOST: db
      PGUSER: postgres
  rabbitmq:
    restart: always
    image: rabbitmq:3.8.2-management
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  db_data:
  rabbitmq: